# Generated by Django 3.1.2 on 2021-01-03 23:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 1, 3, 23, 56, 48, 229085, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
