# Generated by Django 3.1.2 on 2021-02-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20210110_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Branding Identity', 'Branding Identity'), ('Product Design', 'Product Design'), ('Package', 'Package'), ('Communication', 'Communication'), ('Campaign', 'Campaign'), ('Flyers', 'Flyers')], max_length=200, null=True),
        ),
    ]
