# Generated by Django 3.1.2 on 2021-02-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='brief',
            field=models.CharField(max_length=30),
        ),
    ]
