# Generated by Django 3.1.2 on 2021-02-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210207_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('All', 'All'), ('Branding Identity', 'Branding Identity'), ('Product Design', 'Product Design'), ('Package', 'Package'), ('Communication', 'Communication'), ('Campaign', 'Campaign'), ('Flyers', 'Flyers')], max_length=200, null=True),
        ),
    ]
